#!/bin/bash

RED="\e[01;31m"
YELLOW="\e[01;33m"
GREEN="\e[01;32m"
CLEAR="\e[0m"
ALL=""
WARNING=""

while getopts "aw" opt
do
	case "${opt}" in
		a)
			ALL="-a"
			;;
		w)
			WARNING="-w"
			;;
	esac
done



UTILS="./utils"
CSV_SRC="./csvFiles"
TCG_SRC="${CSV_SRC}/tcgfiles"
INFO_SRC="${CSV_SRC}/infofiles"
HTML_SRC="./docs"

TCGINFO_SRC="${INFO_SRC}/setsinfo.csv"
INFO_CONTENT=`cat ${TCGINFO_SRC}`

TEMPLATE=`cat docs/template.html`

MENU_CONTENT="<h3>TCG Sets</h3>\n<table id=\"menutable\">\n<tr>\n"
TABLE_WIDTH=3
CURR_TD=1

while IFS=',' read -r SET_NAME SET_YEAR SET_TOTAL SET_COUNT SET_NUM SET_CATEGORY SET_COMPLETE SET_SUBSET
do
	SET_FNAME="$(echo "${SET_NAME}" | tr -d '[:space:]' | tr '[:upper:]' '[:lower:]')"
	if [[ -n "${SET_SUBSET}" ]]
	then
		SUBSET_FNAME="$(echo "${SET_NAME}_${SET_SUBSET}" | tr -d '[:space:]' | tr '[:upper:]' '[:lower:]')"
	else
		SUBSET_FNAME="${SET_FNAME}"
	fi

	SET_CSV="${TCG_SRC}/${SUBSET_FNAME}.csv"
	SET_IMG="images/sets/${SET_FNAME}.png"
	SET_TITLEIMG="images/sets/${SET_FNAME}title.png"
	SET_HTML="${SUBSET_FNAME}.html"

	if [ "${SET_COMPLETE}" == "True" ]
	then
		SET_TDCLASS="complete"
	else
		SET_TDCLASS="incomplete"
	fi

	if [[ -n "${SET_SUBSET}" ]]
	then
		TITLESPAN="<div class=\"titlediv\"><b>${SET_NAME}</b><br><i>${SET_SUBSET}</i></div>"
	else
		TITLESPAN="<div class=\"titlediv\"><b>${SET_NAME}</b></div>"
	fi
	SET_LINK="<td class=\"${SET_TDCLASS}\"><a href=\"${SET_HTML}\"><div class=\"content\"><div class=\"imgdiv\"><img src=\"${SET_IMG}\"></div>${TITLESPAN}</div></a></td>\n"
	MENU_CONTENT="${MENU_CONTENT}${SET_LINK}"

	if [ ${CURR_TD} -lt ${TABLE_WIDTH} ]
	then
		CURR_TD=$(( CURR_TD + 1 ))
	else
		CURR_TD=1
		MENU_CONTENT="${MENU_CONTENT}\n</tr>\n<tr>"
	fi

	ERRORS="$(awk -f "${UTILS}/validate_set.awk" "${SET_CSV}")"
	EXIT="$?"
	if [[ "${EXIT}" == 2 ]]
	then
		echo -e "${RED}ERROR:${CLEAR} Invalid CSV for ${SET_NAME}"
		echo "${ERRORS}" | sed 's/^/\t/'
		continue
	elif [[ "${EXIT}" == 1 ]] &&
	     [[ -n "${WARNING}" ]]
	then
		echo -e "${YELLOW}WARNING:${CLEAR} Potential Errors in CSV for ${SET_NAME}"
		echo "${ERRORS}" | sed 's/^/\t/'
	fi

	if [[ ! -e "${SET_CSV}" ]]
	then
		echo -e "${RED}ERROR:${CLEAR} No CSV for ${SET_NAME}"
		continue
	elif [[ ! -e "${HTML_SRC}/${SET_IMG}" ]]
	then
		echo -e "${RED}ERROR:${CLEAR} No Set Img for ${SET_NAME}"
		continue
	elif [[ ! -e "${HTML_SRC}/${SET_TITLEIMG}" ]]
	then
		echo -e "${RED}ERROR:${CLEAR} No Set Title Img for ${SET_NAME}"
		continue
	fi

	if [[ -z "${ALL}" ]] &&
	   [[ -e "${HTML_SRC}/${SET_HTML}" ]] &&
	   [[ "${HTML_SRC}/${SET_HTML}" -nt "${SET_CSV}" ]]
	then
		continue
	fi

	SET_TABLE="$(awk -f "${UTILS}/setTable.awk" "${SET_CSV}" "${SET_COUNT}")"

	HTML_CONTENT="<img src=\"${SET_TITLEIMG}\" id=\"set_title_img\">\n<br>\n<hr>\n"
	HTML_CONTENT="${HTML_CONTENT}${SET_TABLE}"

	HTML_PAGE=${TEMPLATE}
	HTML_PAGE="${HTML_PAGE/<!-- CONTENT -->/${HTML_CONTENT}}"
	echo -e "${HTML_PAGE}" > "${HTML_SRC}/${SET_HTML}"

	echo -e "${GREEN}Built ${SET_NAME}${CLEAR}"
done < <(tail -n +2 "${TCGINFO_SRC}")

MENU_CONTENT="${MENU_CONTENT}\n</tr>\n</table>\n"

MENU_CONTENT="${MENU_CONTENT}<h3>Other Sets</h3>\n<table>\n<tr>\n"

echo "Starting half decks..."

HD_TABLE=`awk -f ${UTILS}/halfdeckTable.awk ${TCG_SRC}/halfdecks.csv`
HTML_CONTENT="<h2>Half Decks</h2> ${HD_TABLE}"
HTML_PAGE=${TEMPLATE}
HTML_PAGE="${HTML_PAGE/<!-- CONTENT -->/${HTML_CONTENT}}"
echo "${HTML_PAGE}" > ${HTML_SRC}/halfdecks.html
echo "  Built HTML file"

MENU_CONTENT="${MENU_CONTENT}<td><a href=\"halfdecks.html\">Half Decks</a></td>"
echo "  Added to Menu"

echo "Completed half decks"

echo "Starting Black Star Promos"

PROMO_TABLE=`awk -f ${UTILS}/bspromoTable.awk ${TCG_SRC}/promo.csv`
HTML_CONTENT="<h2>Black Star Promos</h2> ${PROMO_TABLE}"
HTML_PAGE=${TEMPLATE}
HTML_PAGE="${HTML_PAGE/<!-- CONTENT -->/${HTML_CONTENT}}"
echo "${HTML_PAGE}" > ${HTML_SRC}/promo.html
echo "  Built HTML file"

MENU_CONTENT="${MENU_CONTENT}<td><a href=\"promo.html\"><img src=\"images/general/promo.png\"> Black Star Promo</a></td>"
echo "  Added to Menu"

echo "Completed Black Star Promos"

echo "Starting Pop Series Promo"

PROMO_TABLE=`awk -f ${UTILS}/poppromoTable.awk ${TCG_SRC}/popseriespromo.csv`
HTML_CONTENT="<h2>Pop Series Promos</h2> ${PROMO_TABLE}"
HTML_PAGE=${TEMPLATE}
HTML_PAGE="${HTML_PAGE/<!-- CONTENT -->/${HTML_CONTENT}}"
echo "${HTML_PAGE}" > ${HTML_SRC}/popseriespromo.html
echo "  Built HTML file"

MENU_CONTENT="${MENU_CONTENT}<td><a href=\"popseriespromo.html\">Pop Series Promo</a></td></tr>"
echo "  Added to Menu"

echo "Completed Pop Series Promo"

echo "Starting Non-English Cards"
PROMO_TABLE=`awk -f ${UTILS}/setTable.awk ${TCG_SRC}/othercards.csv`
HTML_CONTENT="<h2>Non-English Cards</h2> ${PROMO_TABLE}"
HTML_PAGE=${TEMPLATE}
HTML_PAGE="${HTML_PAGE/<!-- CONTENT -->/${HTML_CONTENT}}"
echo "${HTML_PAGE}" > ${HTML_SRC}/nonenglish.html
echo "  Built HTML file"

MENU_CONTENT="${MENU_CONTENT}<td><a href=\"nonenglish.html\">Non-English Cards</a></td>"
echo "  Added to Menu"

echo "Completed Non-English Cards"

echo "Starting Topps Chrome"
PROMO_TABLE=`awk -f ${UTILS}/toppsTable.awk ${CSV_SRC}/otherfiles/toppschrome.csv`
HTML_CONTENT="<h2>Topps Chrome</h2> ${PROMO_TABLE}"
HTML_PAGE=${TEMPLATE}
HTML_PAGE="${HTML_PAGE/<!-- CONTENT -->/${HTML_CONTENT}}"
echo "${HTML_PAGE}" > ${HTML_SRC}/toppschrome.html
echo "  Built HTML file"

MENU_CONTENT="${MENU_CONTENT}<td><a href=\"toppschrome.html\">Topps Chrome</a></td></tr>"
echo "  Added to Menu"

echo "Completed Topps Chrome"



INDEX=${TEMPLATE}
INDEX="${INDEX/<!-- CONTENT -->/${MENU_CONTENT}}"

echo -e "${INDEX}" > docs/index.html


